---
title: "Reproducible Research Data Science Guide"
subtitle: "Version 1.0"
author:
  - name: "Jen Fisher and Avery Williams, Lasseigne Lab, CDIB, UAB"
  - name: "Developed with assistance from the Lasseigne Lab and Dr. Lara Ianov, UAB"
    affiliation: For questions, email Dr. Lasseigne at bnp0001@uab.edu
date: "4/24/2020"
output:
  html_document:
    theme: spacelab
    toc: yes
    toc_float:
      collapsed: no
      smooth_control: yes
  pdf_document:
    toc: yes
---

# Dry Lab Notebooks
We generally follow, and encourage others to follow, <a href="https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004385" target="_blank">Ten Simple Rules for a Computational Biologist's Laboratory Notebook</a>.

Lab notebooks provide a complete record of procedures, reagents, data, and thoughts, as well as an explanation of why/how you are doing an experiment and its results. Our lab uses <a href="https://www.evernote.com" target="_blank">Evernote</a> as an online lab notebook with scripts and projects managed in GitHub repositories attached inside.

We recommend taking note of the following in your daily and/or dry lab experiment notebook:

* The goal/purpose of the experiment and/or operations
* Systems where the operations were done
  * (e.g. personal laptop or Cheaha)
* Directory of operations
* Names and locations of scripts and when they were edited or used
* Information on and location of raw data
* A description of steps like a paragraph for a paper
* Any important screenshots, figures, or presentations related to a project
* Dates of operations
* Versions of programming languages, tools, and/or packages

---

# R Projects
One can use R Projects that can be linked to version control programs such as Git (which is covered later in the guide) to create and manage reproducible data.

## R and RStudio
See <a href="https://www.lasseigne.org/education/education_resources/rmasterguide.html" target="_blank"> this R Master Guide</a> for a full introduction to R and RStudio.

## R Markdown
<a href="https://rmarkdown.rstudio.com/" target="_blank">R Markdown</a>, a tool in RStudio, creates reproducible documents that can combine narrative text and code from languages such as R, Python, and SQL. See below for some helpful resources:

* <a href="https://rmarkdown.rstudio.com/lesson-1.html" target="_blank">RStudio's R Markdown Guide</a>
* <a href="https://rstudio.com/wp-content/uploads/2016/03/rmarkdown-cheatsheet-2.0.pdf" target="_blank">RStudio's R Markdown Cheat Sheet</a>
* <a href="https://github.com/tchapi/markdown-cheatsheet/blob/master/README.md" target="_blank"> Cyril Chappellier's Markdown Cheat Sheet</a>

It might be helpful to add a sessionInfo() function at the bottom of Rmarkdown files in order to help people know what version of R and its packages you are using. You can also use <a href="https://rstudio.github.io/packrat/" target="_blank">this</a> package, titled "packrat", for R package version control, which allows versions of packages to be shared with others.

#### Software Carpentry Tutorials 
<a href="http://swcarpentry.github.io/r-novice-gapminder/" target="_blank">These lessons</a>, titled "R for Reproducible Scientific Analysis," were covered in the aforementioned R Master Guide but are particularly helpful in learning how to code for data analysis and setting a good workflow. Take a look at the lesson plan to see what specific lessons fit your needs. 

---

# Git
<a href="https://git-scm.com/" target="_blank">Git</a> is a free, open source distributed version control system. It tracks changes, maintains history, and allows you to revert changes. Clones will mirror the full history of the original repository. For more information on this as well as an overview of different version control systems, check out <a href="https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control#:~:text=Version%20control%20is%20a%20system,of%20file%20on%20a%20computer" target="_blank">this</a> chapter of the Git documentation book.

For an overview of the different version control systems and a brief explanation of what makes git a distributed

## GitHub 
<a href="https://github.com" target="_blank">Github</a> uses Git to allow software development version control to manage changes to scripts through a push/pull system. It is a very useful tool for both individual and team version control, with settings to allow others to view your code for collaboration and/or reproducibility. Below are some GitHub tutorials you can follow:

* Coding Club's <a href="https://ourcodingclub.github.io/tutorials/git-for-labs/" target="_blank">Setting up a GitHub Repository For Your Lab - Version Control & Code Management with GitHub</a>
* Software Carpentry's <a href="http://swcarpentry.github.io/git-novice/" target="_blank">Version Control with Git</a>
* Jennifer Bryan's <a href="https://happygitwithr.com/index.html" target="_blank">Happy Git and GitHub for the useR</a>

## GitLab
<a href="https://about.gitlab.com/" target="_blank">GitLab</a> also uses Git and is a service that allows access to private pipelines for free. It has seamless migration to/from GitHub, and it has an RStudio integration. Below are some resources explaining GitLab, as well as some clarifying the differences between it and GitHub:

* <a href="https://gitlab.rc.uab.edu/" target="_blank">UAB Research Computing's GitLab</a>, which provides free unlimited private repos
* <a href="https://gitlab.rc.uab.edu/lianov/gitlab_demo/-/blob/master/GitLab_presentation.pdf?expanded=true&viewer=rich" target="_blank">Dr. Lara Ianov's presentation on GitLab</a>
* <a href="https://about.gitlab.com/devops-tools/github-vs-gitlab.html" target="_blank">About GitLab - GitHub vs GitLab</a>

---

# Data Management
_This section provides steps you can follow for general data management and storage._

## General Steps
* Back up your data. A general rule to follow is to have three different storage locations.
  * (e.g. on your computer, on Google Drive or a cloud-based location, and on an external hard drive or lab server)
* Make sure you have at least one cloud and one off-site storage space for your data and scripts.
* Keep data and scripts organized within a directory or workspace. There should be different directories for raw data, scripts, results, and/or documents, but this can vary by project.
* Include frequent comments in your code. This is important for keeping it clear for both yourself in the future and for others reviewing it.
* When creating a new directory, start with the date (in order to make them sortable by date), then a project title or description.
  * (e.g. 190811_projectname for a project started on 8/11/2019)
* When naming files, start with the date, then a title or short description of the script.
  * (e.g. 190811_rna_seq_analysis)
* In your scripts, it is important to include:
  * The person who wrote the script
  * Date(s) of operations of the script
  * A description of the purpose of the script
  * Comments about operations done within the script
* Create an overview text document in your workspace describing the project, organization of the directory, and locations of data.
  * (e.g. a GitHub README.md)
* Create and check md5sum files to check if your data files have changed after computational operations (more on that <a href="https://www.google.com/url?q=https://www.tecmint.com/generate-verify-check-files-md5-checksum-linux/&sa=D&ust=1588690772609000&usg=AFQjCNG0MBCdTTQljp_CpyRKkaL_NhRMPQ" target="_blank">here</a>).
* Use a method for version control or note what versions of tools were used for computational operations.

## Storage of Scripts
RStudio projects, scripts, and some small files should be stored in a GitHub project/repository as well as a backup location.

## Storage of Large Data
### Cheaha
<a href="https://docs.uabgrid.uab.edu/wiki/Cheaha" target="_blank">Cheaha</a> is UAB's cluster computing environment. You can learn more about it in <a href="https://www.youtube.com/watch?v=6M-OPA9I8S8&list=PLfodFxaCrr0eyWHvZYJr1fdMJlSrECpxt" target="_blank">this</a> youtube video.

* This would be used for large data that needs a supercomputer.
* ***Cheaha is not a backed up resource.***

#### Tools for Data Transfer
* The tool "rclone" can be used on Cheaha for copying/moving files to and from cloud storage in Google Drive, Box, and other cloud services. Here are some useful resources:
  * <a href="https://docs.uabgrid.uab.edu/wiki/Box.com_bulk_transfer" target="_blank">UAB's Wiki on transferring between Cheaha and Box with rclone</a>
    * <a href="https://www.youtube.com/watch?v=UbFJV9TO4KE&feature=youtu.be" target="_blank">Video demonstration
  * <a href="https://rclone.org/drive/" target="_blank">rclone for Google Drive</a>
  * <a href="https://rclone.org/commands/" target="_blank">rclone commands</a>
* The tool "Globus" can be used for secure data transfer and can be done between remote locations (e.g.: a collaborator's computer to Cheaha and vice-versa). For more information on utilizing Globus with your UAB BlazerID, visit <a href="https://docs.uabgrid.uab.edu/wiki/Globus" target="_blank"> this link</a>
  
#### Data Storage Locations and Functions
* /data/project/lab_name/ (50TB)
  * storage of raw data, genome information files, and storage of results
  * a lab must send a ticket to Research Computing requesting that project directory be created
* /scratch/username (shared storage - meant for short-term storage during analysis)
  * workspace: copy raw files here to work with, then copy results to the lab project folder or /data/user/username once you are done
* /data/user/username (5-10TB)
  * files for an individual, such as R libraries or individual projects
* /home/username (20-50GB)
  * limited space, but some important files for programs might need to be stored here
      (e.g. ".Renviron" for R and RStudio instructions in the cluster)
* More information about storage locations on the cluster can be found <a href="https://docs.uabgrid.uab.edu/wiki/Cheaha2_GettingStarted#Storage" target="_blank">here</a>.

#### Getting Started with Cheaha 
1. Follow <a href="https://docs.uabgrid.uab.edu/wiki/Cheaha_GettingStarted" target="_blank">this link</a> for an in-depth guide on getting started on Cheaha.
2. To request an account, send an email to <a href="mailto:support@listserv.uab.edu" target="_blank">support@listserv.uab.edu</a> with background on your intended use and your affiliations.
3. Acknowledge the confirmation email to submit the account request.
4. Follow <a href="https://docs.uabgrid.uab.edu/wiki/Cheaha2_GettingStarted#Example_Batch_Job_Script" target="_blank">this</a> Hello World example.
5. Make RLibs and RStudioLibs folders for R packages in the /data/user/username folder to prevent packages from being stored in the home directory.
  
#### Pipeline Tools and Virtual Environments
These tools should be used for version control for tool and workflow management on Cheaha to ensure reproducibility and scalability.

*Anaconda*: an integrated tool used to build the environment the pipeline runs on. It installs programs into the working directory and allows you to view and change which versions programs are utilizing.

* Learn about using Anaconda for version control <a href="https://docs.uabgrid.uab.edu/wiki/anaconda" target="_blank">here</a>.
* To learn more about creating an Anaconda environment on Cheaha, watch <a href="https://www.youtube.com/watch?v=tfGJlO9AeXU" target="_blank">this</a> video.

*Snakemake*: built on a make system that ensures that files are produced for each appropriate step, ensuring every expected output is produced. You can rerun a step by deleting the output from that step and the pipeline will rerun from that point.

* Learn more about the tool Snakemake <a href="https://vincebuffalo.com/blog/2020/03/04/understanding-snakemake.html" target="_blank">here</a>

### Lab Google Drive
Our lab uses a <a href="https://www.google.com/drive/" target="_blank">Google Drive</a> folder, where data is organized into subfolders by project.

### Box
<a href="https://www.box.com/home" target="_blank">Box</a> is a cloud storage service that is free to UAB staff. <a href="https://www.uab.edu/it/home/tech-solutions/file-storage/box/?utm_source=golink&utm_medium=golink" target="_blank">**UAB will be discontinuing its use of Box in 2021**</a>. *This section will be updated as UAB IT releases more information on this topic.*

* <a href="https://www.uab.edu/it/home/box" target="_blank">UAB's Box Landing Page</a>
* <a href="https://support.box.com/hc/en-us/articles/360044196373-The-Basics-of-Box" target="_blank">The Basics of Box</a>

### External Hard Drives
Our lab uses G-Drives, but one needs to be aware of how a given drive is formatted, as this will affect how well it works with different computing platforms. We label these drives with our initials as well as additional labels as needed and a description of what is in the hard drive. Other options are Seagate and other reputable brands with extensive reviews. As external drives are a physical storage device for data, it is important to choose a trustworthy brand and model that is compatible with your needs.

## Other Resources

* <a href="https://github.com/greenelab/onboarding/blob/master/onboarding.md#source-code-data-and-reproducibility" target="_blank">Greene Lab's Data Management Policies</a>
* <a href="https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004525" target="_blank">Ten Simple Rules for Creating a Good Data Management Plan</a>
* <a href="https://library.ucsd.edu/research-and-collections/data-curation/best-practices.html" target="_blank">Data Management Best Practices</a>
* <a href="https://guides.ucsf.edu/c.php?g=101037&p=2704713" target="_blank">Reproducible Data Management</a>
* <a href="https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510" target="_blank">Good Enough Practices in Scientific Computing</a>